apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: microservices-app
  labels:
    app: book-service
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      name: http
    - port: 9010
      targetPort: 9010
      name: jmx
  selector:
    app: book-service