apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: microservices-app
  labels:
    app: config-server
spec:
  ports:
    - port: 8888
      targetPort: 8888
      name: http
  selector:
    app: config-server