apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: microservices-app
  labels:
    app: consul
spec:
  type: NodePort
  ports:
    - port: 8500
      targetPort: 8500
      name: http
      nodePort: 30500
  selector:
    app: consul