apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: consul-token-updater-rb
  namespace: microservices-app
subjects:
  - kind: ServiceAccount
    name: consul-token-updater-sa
    namespace: microservices-app
roleRef:
  kind: Role
  name: consul-token-updater-role
  apiGroup: rbac.authorization.k8s.io