apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  namespace: microservices-app
  labels:
    app: consul
spec:
  serviceName: "consul"
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: dmfan/consul:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8500
              name: http
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "0.5"
          volumeMounts:
            - name: consul-data
              mountPath: /consul/data/
          readinessProbe:
            httpGet:
              path: /v1/status/leader
              port: 8500
            initialDelaySeconds: 10
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: consul-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi