apiVersion: v1
kind: Service
metadata:
  name: file-db
  namespace: microservices-app
  labels:
    app: file-db
spec:
  ports:
    - port: 27017
      name: mongo
  clusterIP: None
  selector:
    app: file-db