apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: file-db
  namespace: microservices-app
  labels:
    app: file-db
spec:
  serviceName: "file-db"
  replicas: 1
  selector:
    matchLabels:
      app: file-db
  template:
    metadata:
      labels:
        app: file-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
              name: mongo
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "0.7"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom: { secretKeyRef: { name: app-secrets, key: MONGODB_USER } }
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secrets, key: MONGODB_PASSWORD } }
            - name: MONGO_INITDB_DATABASE
              valueFrom: { secretKeyRef: { name: app-secrets, key: MONGODB_DB_NAME } }
            - name: MONGODB_USER
              valueFrom: { secretKeyRef: { name: app-secrets, key: MONGODB_USER } }
            - name: MONGODB_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secrets, key: MONGODB_PASSWORD } }
            - name: MONGODB_DB_NAME
              valueFrom: { secretKeyRef: { name: app-secrets, key: MONGODB_DB_NAME } }
          volumeMounts:
            - name: file-db-data
              mountPath: /data/db
            - name: file-db-init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          readinessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
                - --quiet
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            exec:
              command:
                - mongosh
                - --eval
                - "db.adminCommand('ping')"
                - --quiet
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: file-db-init
          configMap:
            name: file-db-init-scripts
            items:
              - key: init-mongo.sh
                path: init-mongo.sh
  volumeClaimTemplates:
    - metadata:
        name: file-db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 3Gi