apiVersion: v1
kind: Service
metadata:
  name: file-service
  namespace: microservices-app
  labels:
    app: file-service
spec:
  ports:
    - port: 8083
      targetPort: 8083
      name: http
  selector:
    app: file-service