apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: microservices-app
  labels:
    app: gateway
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort: 30080
  selector:
    app: gateway