apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-service
  namespace: microservices-app
  labels:
    app: jwt-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-service
  template:
    metadata:
      labels:
        app: jwt-service
    spec:
      initContainers:
        - name: wait-for-consul-token
          image: busybox:1.35
          imagePullPolicy: IfNotPresent
          command: [ 'sh', '-c', 'echo "Checking for /consul/data/service_token.txt..."; while [ ! -s "/consul/data/service_token.txt" ]; do sleep 2; done; echo "Token file found."' ]
          volumeMounts:
            - name: consul-token-file-mount
              mountPath: /consul/data
              readOnly: true
      containers:
        - name: jwt-service
          image: dmfan/jwt-service:v.1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "0.5"
          env:
            - name: CONFIG_SERVICE_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secrets, key: CONFIG_SERVICE_PASSWORD } }
            - name: JWT_SECRET
              valueFrom: { secretKeyRef: { name: app-secrets, key: JWT_SECRET } }
            - name: CONSUL_HOST
              value: consul
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: consul-token-file-mount
              mountPath: /consul/data/service_token.txt
              subPath: service_token.txt
              readOnly: true
      volumes:
        - name: consul-token-file-mount
          secret:
            secretName: consul-client-token-secret
            items:
              - key: CONSUL_HTTP_TOKEN
                path: service_token.txt