apiVersion: v1
kind: Service
metadata:
  name: jwt-service
  namespace: microservices-app
  labels:
    app: jwt-service
spec:
  ports:
    - port: 8084
      targetPort: 8084
      name: http
  selector:
    app: jwt-service