apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: microservices-app
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      name: plaintext
  clusterIP: None
  selector:
    app: kafka