apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices-app
type: Opaque
data:
  # echo -n 'your_password' | base64
  CONFIG_SERVICE_PASSWORD: <base64-encoded-config-service-password>
  POSTGRE_USERS_PASS: <base64-encoded-postgres-users-password>
  POSTGRE_USERS_USER: <base64-encoded-postgres-users-username>
  POSTGRE_USERS_DB_NAME: <base64-encoded-postgres-users-db-name>
  POSTGRE_BOOKS_PASS: <base64-encoded-postgres-books-password>
  POSTGRE_BOOKS_USER: <base64-encoded-postgres-books-username>
  POSTGRE_BOOKS_DB_NAME: <base64-encoded-postgres-books-db-name>
  MONGODB_PASSWORD: <base64-encoded-mongo-password>
  MONGODB_USER: <base64-encoded-mongo-username>
  MONGODB_DB_NAME: <base64-encoded-mongo-db-name>
stringData:
  JWT_SECRET: "<64-byte-length-base64-encoded-jwt-sign-key>"