server:
  port: 8082  # Порт book-service

spring:
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        generate-ddl: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${BOOKS_DB_CONTAINER_NAME:localhost}:6542/${POSTGRE_BOOKS_DB_NAME}
    username: ${POSTGRE_BOOKS_USER}
    password: ${POSTGRE_BOOKS_PASS}

  sql.init:
    mode: always
    schema-locations: classpath:schema.sql