server:
  port: 8082  # Порт book-service

spring:
  kafka:
    bootstrap-servers: ${KAFKA_CONTAINER_NAME:localhost}:9092
    consumer:
      # Идентификатор группы потребителей
      group-id: ${spring.application.name}
      # Стратегия чтения сообщений
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        generate-ddl: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${BOOKS_DB_CONTAINER_NAME:localhost}:6542/${POSTGRE_BOOKS_DB_NAME}
    username: ${POSTGRE_BOOKS_USER}
    password: ${POSTGRE_BOOKS_PASS}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    liquibase-schema: public
  sql.init:
    mode: never
    schema-locations: classpath:schema.sql