spring:
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/v1/books/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: file-service
          uri: lb://FILE-SERVICE
          predicates:
            - Path=/api/v1/files/**
server:
  port: 8080  # Порт Gateway